server:
  port: 6868
management:
  endpoints:
    web:
      exposure:
        include: "*" #expose /actuator/env endpoint (among all others), to show env information
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/user

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: someTpc
          content-type: application/json
        input:
          destination: someTpc
          content-type: application/json
          group: someGrp
      kafka:
        binder:
          brokers: 192.168.50.50