#http://localhost:6767/licsrv/default
server:
  port: 6767
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\Java\springmicroservices\configserver\src\main\resources\config\licsrv
