#default props - e.g. local environment
tracer.property: "DEFAULT"
spring.jpa.database: "default"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://10.10.121.137:33306/crawled"
spring.datasource.username: "root"
spring.datasource.password: "123456"
some.prop: "KRK"
