#default props - e.g. local environment
tracer.property: "DEFAULT"
spring.jpa.database: "default"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://10.10.121.137:33306/crawled"
spring.datasource.username: "root"
spring.datasource.password: "123456"

#use ENCRYPT_KEY env var /decrypt endpoint to decrypt
#need oracle JCE jars
#spring.datasource.password: "{cipher}7310f27988a43a93cbeedd8560ff798df2e8a8553ede18b0d96ea7dcd43df1cb"
some.prop: "SOME_PROP_APPEND"
